apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservices-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: AuthServices
  template:
    metadata:
      labels:
        app: AuthServices
    spec:
      containers:
      - name: authservicesrepos
        image: truyumcr.azurecr.io/authservicesrepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn

---
apiVersion: v1
kind: Service
metadata:
  name: movielist
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: AuthServices